name: 'Download Build Artifacts using RegExp'
description: 'Find via RegExp and Download build artifacts that was previously uploaded in the workflow by the upload-artifact action'
author: 'GitHub && ElonH'
inputs: 
  pattern:
    description: 'Artifact name pattern'
    required: false
  path:
    description: 'Destination path'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
